### PR TITLE
fix: Support class features when transforming source code

### LINKED ISSUE #199: `TypeError: this[statement.type] is not a function`
I got the following error trying to map `@appland/models` as of a41b670ae170303cc46f74a2d6afb535eaa9dbd9:
```
FAIL  tests/unit/appMapFilter.spec.js
  ● Test suite failed to run

    TypeError: this[statement.type] is not a function

      at Object.BlockStatement (file:/home/divide/projects/appmap-js/node_modules/astring/dist/astring.mjs:286:29)
      at Object.ClassDeclaration (file:/home/divide/projects/appmap-js/node_modules/astring/dist/astring.mjs:529:10)
      at Object.Program (file:/home/divide/projects/appmap-js/node_modules/astring/dist/astring.mjs:261:27)
      at generate (file:/home/divide/projects/appmap-js/node_modules/astring/dist/astring.mjs:1178:29)
      at instrument$2 (file:/home/divide/projects/appmap-js/node_modules/@appland/appmap-agent-js/dist/bundles/transformer-jest.mjs:2726:18)
      at instrument$1 (file:/home/divide/projects/appmap-js/node_modules/@appland/appmap-agent-js/dist/bundles/transformer-jest.mjs:2808:37)
      at instrument (file:/home/divide/projects/appmap-js/node_modules/@appland/appmap-agent-js/dist/bundles/transformer-jest.mjs:3089:55)
      at transform (file:/home/divide/projects/appmap-js/node_modules/@appland/appmap-agent-js/dist/bundles/transformer-jest.mjs:3176:13)
      at processAsync (file:/home/divide/projects/appmap-js/node_modules/@appland/appmap-agent-js/dist/bundles/transformer-jest.mjs:3239:16)
      at ScriptTransformer.transformSourceAsync (../../node_modules/@jest/transform/build/ScriptTransformer.js:676:25)
```

### PR DESCRIPTION
**Pull request by dividedmind**
appmap-agent-js uses @babel/parser to parse the ECMAScript code for transformation; the output generated by that library is not 100% estree-compliant [1]. It has an `estree` plugin that reverts the deviations; however, by default not all of them are supported (apparently for @babel/parser's own backward compatibility reasons). Fortunately it has a config setting that enables them.

One of these differences is that the standard node type of PropertyDefinition is called ClassProperty instead, which made the transformer unable to correctly handle ES classes.

[1] https://babeljs.io/docs/babel-parser#output

Fixes #199

### CODE REVIEW

**Comment by lachrist** [comment]
The official name is `MethodDefinition` and not `PropertyDefinition`. It would be good to verify in testing that `astring` is handling it.
```
> require("acorn").parse("class c { m () {} }").body[0].body.body[0].type
'MethodDefinition'
```

https://github.com/estree/estree/blob/master/es2015.md#methoddefinition

**Comment by lachrist** [comment]
It will be probably worthwhile to move to a babel-only format so that we do not have to rely to the less used `astring` and use `@babel/generator` instead. I tried doing that but it requires some non-trivial changes on the instrumentation visitors.

**Review by lachrist — CHANGES_REQUESTED** [review]
Good work!
Let's check that `astring` is handling `PropertyDefinition` first before merging.

**Comment by dividedmind** [comment]
> The official name is `MethodDefinition` and not `PropertyDefinition`. It would be good to verify in testing that `astring` is handling it.
> 
> ```
> > require("acorn").parse("class c { m () {} }").body[0].body.body[0].type
> 'MethodDefinition'
> ```
> 
> https://github.com/estree/estree/blob/master/es2015.md#methoddefinition

MethodDefinition is a different thing. This is about PropertyDefinition: https://github.com/estree/estree/blob/master/es2022.md#propertydefinition

**Comment by dividedmind** [comment]
> Good work! Let's check that `astring` is handling `PropertyDefinition` first before merging.

Added a test on the instrumentation side.

**Comment by dividedmind** [comment]
> It will be probably worthwhile to move to a babel-only format so that we do not have to rely to the less used `astring` and use `@babel/generator` instead. I tried doing that but it requires some non-trivial changes on the instrumentation visitors.

I don't think that's a good idea unless it's really necessary. It will make it more difficult if we want to switch the parser and/or generator in the future.

**Comment by lachrist** [comment]
> > It will be probably worthwhile to move to a babel-only format so that we do not have to rely to the less used `astring` and use `@babel/generator` instead. I tried doing that but it requires some non-trivial changes on the instrumentation visitors.
> 
> I don't think that's a good idea unless it's really necessary. It will make it more difficult if we want to switch the parser and/or generator in the future.

Yeah it is really unfortunate that babel defined its own ast format. Let's keep it like this for the moment then.

File: component/signature.mjs [hunk 1]
```diff
@@ -84,7 +84,7 @@ const parseBabelLog = (content, url) => {
     return parseBabel(content, {
       sourceType: "module",
       sourceFilename: url,
-      plugins: ["estree"],
+      plugins: [["estree", { classFeatures: true }]],
```
Comment (lachrist) [inline component/signature.mjs:87]: FYI This file is used to build the agent and it does not contain any `PropertyDefinition`. But it is fine to add it as well here.

**Review by lachrist — APPROVED** [review]
Good work, thanks!

**Comment by lachrist** [comment]
> MethodDefinition is a different thing. This is about PropertyDefinition: https://github.com/estree/estree/blob/master/es2022.md#propertydefinition

Arf, I should keep up with the standard :s

File: component/signature.mjs (hunk 1 above)
Comment (dividedmind) [reply component/signature.mjs:87]: I figured, but it turned out in grep and I figured it won't hurt for completeness ;)
